run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  # govet:
  #   check-shadowing removed - deprecated option
  gocyclo:
    min-complexity: 15
  # maligned:
  #   suggest-new: true  # maligned linter is deprecated
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/silouanwright/gh-comment
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
        - unused
    - path: testdata/
      linters:
        - unused
    - path: internal/testutil/
      linters:
        - errcheck
        - bodyclose
        - unused
    - path: test/
      linters:
        - errcheck
        - bodyclose
    - path: src/
      linters:
        - unused
    - path: cmd/integration_testing.go
      linters:
        - errcheck
        - bodyclose
    - path: cmd/export.go
      linters:
        - errcheck

  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # Ignore overly strict linting rules for development
    - "cyclomatic complexity .* of func .* is high"
    - "string .* has .* occurrences, make it a constant"
    - "commentedOutCode: may want to remove commented-out code"
    - "appendCombine: can combine chain of .* appends into one"
    - "at least one file in a package should have a package comment"
    - "Potential file inclusion via variable"
    - "Expect directory permissions to be 0750 or less"
    - "Expect WriteFile permissions to be 0600 or less"
    - "var .* is unused"
    - "func .* is unused"
    - "Error return value of.*is not checked"

  max-issues-per-linter: 0
  max-same-issues: 0
